config/routes.rb
Devdash::Application.routes.draw do

  resources :home
  resources :suggestions do
    collection do
      get 'sugviaui'
    end
  end

  root :to => 'home#index'

end

app/models/suggestion.rb
# This is the model for suggestions

# this is actually optional
#require 'couchrest_model'

class Suggestion < CouchRest::Model::Base
  property :FDLclass, String
  property :appVersion, String
  property :page, String
  property :block, String
  property :suggestion, String
  property :labels, [String]
  property :trackingID, String
  property :testdata, TrueClass, :default => false
  timestamps! # use created_at and updated_at fields
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  def index
    @suggestions = Suggestion.all;
  end
  
  def show
    @suggestion = Suggestion.find(params[:id])
  end

  def new
    @suggestion = Suggestion.new
  end
 
  def sugviaui
    @suggestions = Suggestion.all
  end

  def edit
    @suggestion = Suggestion.find(params[:id])
  end
 
  def create
    @suggestion = Suggestion.new(params[:suggestion])
    @suggestion.labels = params[:clabels].split
    if @suggestion.save
      redirect_to @suggestion, notice: 'Suggestion was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @suggestion = Suggestion.find(params[:id])
    @suggestion.labels = params[:clabels].split
    if @suggestion.update_attributes(params[:suggestion])
      redirect_to @suggestion, notice: 'Suggestion was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @suggestion = Suggestion.find(params[:id]);
    @suggestion.destroy
    redirect_to suggestions_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<p>Welcome to DevDash, User [TODO]

You Can:
<p>-&nbsp;<%= link_to 'Create Suggestions Via UI', :action => 'sugviaui', :controller => 'suggestions' %>
<p>-&nbsp;Propose A Feature
<p>-&nbsp;View A Feature Detail
<p>-&nbsp;View My Features
<p>-&nbsp;View Top Features
<p>--------
<p>-&nbsp;<%= link_to 'View All Suggestions', suggestions_path %>
<p>-&nbsp;<%= link_to 'Create A Suggestion', new_suggestion_path %>

app/views/layouts/_footer.html.erb
<p>Increpreneur, Inc. | Version <%= Devdash::Application.config.version %></p>

app/views/layouts/_header.html.erb
<%=t(:company).titleize + " " + t(:product).titleize%> | <%= link_to 'Home', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= t(:product).titleize%></title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<%= render "layouts/header" %>
                <hr>
		<%= yield %>
                <hr>
		<%= render "layouts/footer" %>
	</body>
</html>

app/views/suggestions/_form.html.erb
<%= form_for(@suggestion) do |f| %>
  <% if @suggestion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@suggestion.errors.count, "error") %> prohibited this suggestion from being saved:</h2>

      <ul>
        <% @suggestion.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :appVersion %><br />
    <%= f.text_field :appVersion %>
  </div>
  <div class="field">
    <%= f.label :page %><br />
    <%= f.text_field :page %>
  </div>
  <div class="field">
    <%= f.label :block %><br />
    <%= f.text_field :block %>
  </div>
  <div class="field">
    <%= f.label :suggestion %><br />
    <%= f.text_area :suggestion, :rows => 5 %>
  </div>
  <div class="field">
    <%= f.label :labels %><br />
    <%= text_field_tag :clabels, @suggestion.labels %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/suggestions/edit.html.erb
<p>Edit suggestion

<%= render 'form' %>

<%= link_to t(:show_sug), @suggestion %> |
<%= link_to t(:go_back), :back %>

app/views/suggestions/index.html.erb
<% if @suggestions.empty? %>
  <p>There are no suggestions, would you like to enter a <%= link_to 'new suggestion', new_suggestion_path %>?

<% else %>
  <p>Suggestions

  <table>
    <tr>
      <th>Page</th>
      <th>Version</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

    <% @suggestions.each do |suggestion| %>
      <tr>
        <td><%= suggestion.page %></td>
        <td><%= suggestion.appVersion %></td>
        <td><%= truncate suggestion.suggestion, :length => 80 %></td>
        <td><%= link_to 'Show Full Suggestion', suggestion %></td>
        <td><%= link_to 'Edit', edit_suggestion_path(suggestion) %></td>
        <td><%= link_to 'Remove', suggestion, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
    <% end %>
  </table>

  <br/>

  <p>Would you like to enter a <%= link_to 'new suggestion', new_suggestion_path %>?
<% end %>

app/views/suggestions/new.html.erb
<p>Create New Suggestion

<%= render 'form' %>

<%= link_to t(:go_back), :back %>

app/views/suggestions/show.html.erb
<p>View Suggestion
<p id="notice"><%= notice %></p>

<p>
<b>App Version:</b>
<%= @suggestion.appVersion %>
</p>

<p>
<b>Page:</b>
<%= @suggestion.page %>
</p>

<p>
<b>Block:</b>
<%= @suggestion.block %>
</p>

<p>
<b>Suggestion:</b>
<%= @suggestion.suggestion %>
</p>


<p>
<b>Labels:</b>
<%= @suggestion.labels.join " " %>
</p>

<p>
<b>Tracking Info:</b>
<%= if @suggestion.trackingID then "Yep" else "Nope" end %>
</p>

<p>
<b>Is This Test Data?:</b>
<%= if @suggestion.testdata then "Yep" else "Nope" end %>
</p>

<%= link_to t(:edit_sug), edit_suggestion_path(@suggestion) %> |
<%= link_to t(:go_back), :back %>

app/views/suggestions/sugviaui.html.erb
<p>Create New Suggestion Via UI

<!-- filters -->
<div id="devdash_svu_filters">
  <p>Filtering:
  <%= select_tag "page", "<option>Red</option><option>Green</option><option>Blue</option>".html_safe, :prompt => "Page" %>
  <%= select_tag "block", "<option>Red</option><option>Green</option><option>Blue</option>".html_safe, :prompt => "Block" %>
</div>

<!-- application page embeddable -->
<iframe width="320" height="480" src="http://localhost:5984/quote/_design/pheet/quotegame_v2.html">

<!-- the rest -->

<p><%= link_to t(:go_back), :back %>